import io,re
S=io.open('CHANTIERS.md',encoding='utf-8').read().split('\n')
def maj(num, etat=None, preuve=None, juge=None, lot=None, demande_plus=None):
    for i,l in enumerate(S):
        if l.startswith('| '+num+' |'):
            c=[x for x in l.split(' | ')]
            assert len(c)==7,(num,len(c))
            if demande_plus: c[2]=c[2]+' '+demande_plus
            if etat: c[3]=etat
            if preuve: c[4]=preuve+' — '+c[4] if not c[4].startswith('v140 : inscrit') else preuve
            if juge: c[5]=juge
            if lot: c[6]=lot+' |'
            S[i]=' | '.join(c); return
    raise Exception(num)
maj('C-083', preuve="v140 (RÉCIDIVE « trop rase ») : LA FOURRURE D’AVANT LES ESSAIS DE HALO — densité ×1 (110 000), poil ×1, reflet d’origine, pointes libres au bord (contour moyen 120,5 pt), sans anneau ni liseré, corps plein, l’ombre à 391,2 ; sur la carte graphique et le secours ; 57 images/s au banc WebKit. Cause : la « densité 3 » de v120–v123 (poils ×0,7 : un aplat) puis la coupe franche de v139. L’EMPREINTE SUIT LE VRAI GESTE : la trace le long du chemin du doigt, large comme le contact ; un appui pose une étoile. Planches : `planche-v140/PLANCHE-1-pelote.png`, `PLANCHE-2-trace.png`. À VALIDER SUR IPHONE (Q441, Q448).",
    juge="redteam_fourrure 9/9 (5/9 avant) · redteam_trace 8/8 (2/8 avant) · redteam_bord 24/24 (F réécrit) · redteam_halo 12/12 · redteam_enfonce · redteam_plein", lot='v140')
maj('C-085', preuve="v140 : la photo REMPLACE le dessin de la bande (et inversement), sans reste — cause de la « bande parasite » nommée (les deux vivaient ensemble, la couche du dessin s’arrête 7 pt au-dessus du trait) ; « Enregistrer la photo » devient l’icône unique (C-091).", juge="redteam_remplace 18/18 (8/18 avant) · redteam_cadre · redteam_entier", lot='v140')
maj('C-086', preuve="v140 : le gros pinceau à 22 pt (2 · 6 · 22) ; les trois points : cible de 44 pt chacun, le point = le trait + 3 pt ; dessin ↔ photo par le menu, l’un remplace l’autre ; un dessin partagé emporte ses photos importées (Q435, Tom). Planche : `planche-v140/PLANCHE-3-dessin-photo.png`. À VALIDER SUR IPHONE (Q439).", juge="redteam_remplace 18/18 · redteam_dessin_photo 16/16 (réécrit) · redteam_dessin 79/79", lot='v140')
maj('C-087', preuve="v140 : le disque du + passe de 33 à 45 pt, l’anneau garde 13,5 (72 pt) ; la barre du bas fait 100 pt (730 → 830) : 12 pt d’air au-dessus et au-dessous ; rien d’autre ne bouge à l’écran. Capture cotée : `planche-v140/PLANCHE-5-plus.png` (Q446).", lot='v140')
maj('C-088', preuve="v140 : LE ZOOM DE DÉPART — sous neuf paroles, la parole neuve se plante à côté des autres et la vue cadre les dalles colorées à 0,8 cellule, zoom jusqu’à 3,6 : une dalle entière et un peu autour, puis deux, trois, quatre. Planche à 1, 2, 3, 4 et 9 : `planche-v140/PLANCHE-6-ritournelle.png` (Q445). Le toucher : Tom revérifie (Q438).", lot='v140')
maj('C-074', preuve="v140 : la main « planter » attend que la phrase porte ses mots ; `aura-apparait` est branché (E2bis) : onze gestes branchés, trois recensés.")
maj('C-075', etat='FAIT, EN ATTENTE DE TOM', preuve="v140 : E2 CONSTRUIT (`lot-E2`, `ENGAGEMENT-E2.md`) — prénom (gardé) → le principe → la VRAIE page + (phrase fantôme) → plantation réelle → la fiche (une ligne, la main) → tenir → la dernière ligne → le compte ; « Plus tard » à chaque étape ; textes provisoires sans impératif dans `TEXTES_ENGAGEMENT.e2` ; « TRACE POUR TENIR » 19 px et points Ø 12 ; R6 VERT. Du principe au tenu : 2 touchers et 2 traits (Q442). L’écran « parole et trait » et le message de fin de v129 ne sont plus joués (Q443). Trouvé et corrigé : la phrase perdue après « tenir », le titre sur deux lignes recouvert sur l’instant. Planches : `planche-v140/PLANCHE-8-e2-clair.png`, `-sombre.png`. À VALIDER SUR IPHONE (geste).", juge="redteam_e2 53/53 · redteam_engagement 11/11 · redteam_verrou_onboarding 9/9 (réécrit) · redteam_onboarding (passe la main à redteam_e2)", lot='v140')
maj('C-076', etat='FAIT, EN ATTENTE DE TOM', preuve="v140 : E2bis CONSTRUIT — `promi_devoile` ; le + seul → l’Index à la première plantation → l’Aura au premier tenu (la main la désigne) → le Studio au retour de l’Aura, avec une ligne → le Fil à la première parole adressée ou reçue ; chaque entrée à sa place définitive, la barre s’étire ; rien ne disparaît ; « Plus tard » et le réglage « Tout afficher » affichent tout ; qui n’a pas fait le parcours voit tout (Q444). À VALIDER SUR IPHONE.", juge="redteam_e2 (contrôles D et T) · redteam_gestes", lot='v140')
maj('C-091', etat='FAIT, EN ATTENTE DE TOM', preuve="v140 : UNE ICÔNE, sans texte (la flèche qui descend dans son socle), VoiceOver « Enregistrer » — ① la photo en entier ② le dessin en entier ③ le plateau de l’accueil, à gauche de Partager : l’image de la Toile rendue par le moteur. Pas sur l’écran Partager (Q440). Planche : `planche-v140/PLANCHE-4-enregistrer.png`.", juge="redteam_cadre · redteam_entier · redteam_joignable · redteam_accueil")
maj('C-092', etat='FAIT, EN ATTENTE DE TOM', preuve="v140 : CAUSE NOMMÉE — le panneau flouté du Studio est fait de quatre murs en bandes ; la phrase se centrait dans la bande touchée, et une bande de moins de 40 pt la renvoyait au milieu de l’écran, sur le nom du monde. Au Studio le mur est le PANNEAU ; le panneau des palettes ouvert sur un monde de Ma Parole ! est flouté et mur lui aussi (Q447). Planche : `planche-v140/PLANCHE-7-studio-mur.png`.", juge="redteam_studio_mur 9/9 (3/9 avant) · redteam_murs")
maj('C-093', etat='REPORTÉ', preuve="v140 : ÉCRIT dans `portage/SPEC-DONNEES.md` §5 bis (un document par élément : auteur, rang serveur, ajout seul ; POSER par personne ; signalement et blocage) et `portage/SPEC-ECRANS.md` (la fiche avec dessin). Rien n’est construit ; cinq points À TRANCHER y sont marqués. Reporté au portage, avec Firebase.")
io.open('CHANTIERS.md','w',encoding='utf-8').write('\n'.join(S))
