from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    b=p.webkit.launch()
    ctx=b.new_context(viewport={'width':430,'height':932},device_scale_factor=2,has_touch=True)
    ctx.add_init_script("try{localStorage.setItem('promi_onb','1');localStorage.setItem('promi_rappel_n','9')}catch(e){}")
    pg=ctx.new_page(); pg.on('pageerror', lambda e: print('ERR',str(e)[:200])); pg.goto('http://127.0.0.1:8752/app.html'); pg.wait_for_timeout(6500)
    pg.evaluate("()=>{var o=document.getElementById('promiOnb');if(o){o.classList.add('gone');o.style.display='none';} setTheme('light'); setPremium(true); document.getElementById('createBtn').click()}"); pg.wait_for_timeout(900)
    for k in range(3): pg.evaluate("()=>{const t=document.querySelectorAll('#createSheet .tile')[0]; if(t) t.click();}"); pg.wait_for_timeout(500)
    pg.wait_for_timeout(1600)
    print('classes', pg.evaluate("()=>document.getElementById('createSheet').className"))
    pg.touchscreen.tap(215, 44+120); pg.wait_for_timeout(500); print('sans rien : ouverte', pg.evaluate("()=>_entier.ouverte()"))
    pg.evaluate("()=>window._dessin.ouvre()"); pg.wait_for_timeout(400)
    pg.mouse.move(120,300); pg.mouse.down(); [pg.mouse.move(120+i*9,300+(i%6)*11) for i in range(22)]; pg.mouse.up(); pg.wait_for_timeout(200)
    pg.evaluate("()=>document.querySelector('#dessinMode [data-outil=poser]').click()"); pg.wait_for_timeout(900)
    print('bande', pg.evaluate("()=>{const e=document.querySelector('#createSheet > canvas.dz-bande'); const D=document.getElementById('device').getBoundingClientRect(); if(!e) return null; const r=e.getBoundingClientRect(); const h=document.elementFromPoint(D.left+195,D.top+110); return [r.top-D.top, r.bottom-D.top, h&&(h.id||h.className), document.getElementById('csTrameCv').getAttribute('aria-label')]}"))
    av=pg.evaluate("()=>document.getElementById('createSheet').className+'|'+document.getElementById('createSheet').querySelectorAll('*').length")
    pg.touchscreen.tap(215, 44+110); pg.wait_for_timeout(600); print('toucher la bande : ouverte', pg.evaluate("()=>[_entier.ouverte(), document.querySelector('#entierVue img').naturalWidth, document.getElementById('entierVue').getAttribute('aria-label')]"))
    pg.screenshot(path='scratchpad/v136/entier-plus.png', clip={'x':20,'y':44,'width':390,'height':844})
    pg.touchscreen.tap(215, 400); pg.wait_for_timeout(600); print('second toucher : ouverte', pg.evaluate("()=>_entier.ouverte()"), 'page + intacte', av==pg.evaluate("()=>document.getElementById('createSheet').className+'|'+document.getElementById('createSheet').querySelectorAll('*').length"))
    b.close()
