import io
L=io.open('CHANTIERS.md',encoding='utf-8').read().split('\n')
def maj(num, etat=None, preuve=None, ajoute=None, juge=None, lot=None):
    for i,l in enumerate(L):
        if l.startswith('| %s |'%num):
            c=l.split(' | '); assert len(c)==7, (num,len(c))
            if etat: c[3]=etat
            if preuve is not None: c[4]=preuve
            if ajoute: c[4]=c[4].rstrip()+' '+ajoute
            if juge: c[5]=juge
            if lot: c[6]=lot+' |'
            L[i]=' | '.join(c); return
    raise SystemExit('absent '+num)
maj('C-002','FAIT, EN ATTENTE DE TOM', ajoute="**v130 — cause de la récidive** : le Studio ouvre d'autres contextes WebGL, le navigateur retire celui de la Pelote ; à l'ouverture suivante un canevas neuf était créé et l'ancien `#auBouleGL` restait dans la page, figé, sous le nouveau (un second contour). `peintGL` retire l'ancien avant de poser le neuf. `redteam_zone` passe maintenant par le chemin Aura → Studio (contexte perdu) → Studio → Aura : 12/12 ; rouge sur v129 (trois canevas). Règle inscrite dans CLAUDE.md (v130).", juge='redteam_zone 12/12 (contrôle C)')
maj('C-048','FAIT, EN ATTENTE DE TOM', preuve="**Pourquoi c'est revenu** : ce n'est pas un retour récent (v124 rend la même image) — depuis v29, pour les cinq mondes à trame (Buvard, Braille, Tesselle, Taille-douce, Houle), le moteur peignait la Toile autour de la dalle puis rognait au pixel sur sa cellule : polygone à bords en marches, éclats des voisines (1,2 à 3,5 % des pixels). Le juge ne piégeait que les découpes des écrans, pas celle du moteur. **Corrigé** : chaque peintre n'engendre que la dalle demandée (`_cibleDalle`, `_ENGENDRE`). **Juge** : `redteam_decoupe`, famille G2 (fiche, Index, Fil, fiche d'un Cercle et son fil, défilé compris ; clair et sombre) : 50 dalles jugées, 0 défaut ; rouge sur v129. Interdiction notée dans `portage/A-INTEGRER.md` ; règle dans CLAUDE.md (v130). `banc_rendu` : voir le rapport.", juge='redteam_decoupe (G2)')
maj('C-049','FAIT, EN ATTENTE DE TOM', preuve="**Causes nommées** : ① l'Aura n'était bâtie qu'à son ouverture et `closeAll()` ne lui retire pas `.show` — tenir ou retirer depuis une fiche ouverte par-dessus elle la laissait telle quelle (la liste gardait une parole retirée, n'avait pas celle qu'on venait de tenir) ; ② le Fil gardait les événements d'une parole retirée. **Corrigé à la source** : une signature unique des paroles (`window._paroles`), l'Index, le Fil, l'Aura et le fil du Cercle s'y abonnent (`lot-V130-REACTIF`). `redteam_reactif` 30/30 ; 25/30 sur v129. ⚠ La liste « Ce que tu as tenu » reste bornée à 3 dalles, 6 dès cinq tenues (Q187) : si « incomplète » voulait dire « toutes », c'est une décision à prendre.", juge='redteam_reactif 30/30')
maj('C-050','FAIT, EN ATTENTE DE TOM', preuve="Corps sombre Promi `#8ACBE8` (jeton `--c-tropical78`, JSON = CSS = Swift), fiche Promi et page + d'un Promi ; texte à l'encre `#201908` (9,79:1), Peaufiner et champs de saisie compris. États sur ce corps : à tenir ΔE 103, en cours 76, tenu 70 (seuil 15). **Bande `#82AEF8` contre corps : ΔE CIELAB 28,5 (au-dessus du seuil 15) mais ΔE00 13,1, Δlum 17,6** — à regarder sur la planche `planche-v130/tropical-avant-apres.png` ; aucune des deux couleurs retouchée. ⚠ « Ma Parole ! » (mur du Peaufiner d'un Promi en sombre) n'atteint plus 3:1 sur ce corps. Décision inscrite dans `redteam_decisions` (81/81 ; 70/81 sur v129).", juge='redteam_decisions 81/81 · redteam_tonsurton 26/26')
maj('C-042', ajoute="**v130** : Tom retient la rangée A (sous la bande) ; principe : aucune superposition sur l'espace de dessin. Planche refaite `planche-v130/dessin-{promi,cercle}-{clair,sombre}.png` (mode dessin E1 et E2, tailles, couleurs S1 et S2 ; cotes dans la marge) : rangée à 24 pt sous le trait, tailles et couleurs sous la rangée, les trois lignes descendues de 36 pt (Promi), tout masqué sauf le titre (Cercle) ; 20 cadres sur 20 sans outil dans la bande. Restent à choisir : E1/E2, S1/S2.", lot='v131')
io.open('CHANTIERS.md','w',encoding='utf-8').write('\n'.join(L))
