import io,re
f='CHANTIERS.md'; S=io.open(f,encoding='utf-8').read()
def maj(num, etat, preuve, juge, lot='v139'):
    global S
    m=re.search(r'^\| '+num+r' \|.*$', S, re.M); assert m, num
    c=[x.strip() for x in m.group(0).strip().strip('|').split(' | ')]; assert len(c)==7,(num,len(c))
    c[3]=etat; c[4]=preuve; c[5]=juge; c[6]=lot
    S=S[:m.start()]+'| '+' | '.join(c)+' |'+S[m.end():]
def prefixe(num, texte, etat=None):
    global S
    m=re.search(r'^\| '+num+r' \|.*$', S, re.M); assert m, num
    c=[x.strip() for x in m.group(0).strip().strip('|').split(' | ')]; assert len(c)==7,(num,len(c))
    c[4]=texte+' '+c[4]
    if etat: c[3]=etat
    S=S[:m.start()]+'| '+' | '.join(c)+' |'+S[m.end():]
maj('C-083','FAIT, EN ATTENTE DE TOM',"v139 : ① CONTOUR — une limite franche au rayon de la boule (116 pt), sur la carte graphique et sur le peintre de secours ; frange mesurée sur l’opacité : 0,5 pt (4,25 avant, 6,25 en v136 : il n’y avait pas de « dernier bord net » dans l’historique, Q430) ; le repli de couleur de v137–v138 est retiré ; ΔE bord ↔ intérieur 0,9 à 2,3. ② OMBRE — revenue dans les deux thèmes, géométrie de v121, seule exception de la liste blanche du volume. ③ TOUCHER — profondeur q(t) = 1 − 1/(1 + t/0,60)², retour en 0,60 s, comblement amorti, forme du contact lue sur radiusX/radiusY (ou width/height) ; `?mesure=1` écrit le contact lu. Planche : `planche-v139/PLANCHE-1-pelote.png`. À VALIDER SUR IPHONE (c’est un geste ; constantes à régler, Q432).","redteam_enfonce 14/14 (6/14 avant) · redteam_bord 24/24 par les deux chemins · redteam_halo 12/12 (4/12 avant) · redteam_volume · redteam_plein 97/97 · redteam_contour · redteam_zone 12/12 · releve-aura (acquis 4 réécrit)")
maj('C-084','FAIT, EN ATTENTE DE TOM',"v139 : corps et encart des fiches en clair de #F7F0DE à #EAD9B9 (le fond de l’Index) ; cartes du fil d’un Cercle et carte du mot de #E9D8B7 à #F7F0DE (Q433). Sur #EAD9B9 : encre 12,56:1 · tenu #00341A 10,04:1 · crête 7,46:1 · à tenir #DD4D23 2,93:1 (3,58 avant) · en cours 11,70:1 ; ΔE d’état de 66,8 à 90,4. Trouvé en chemin et corrigé : sur un Chiche tenu en clair, la fin de la phrase était crème sur crème (invisible depuis v136). Planche : `planche-v139/PLANCHE-2-creme.png`.","redteam_decisions 85/85 (réécrit) · redteam_couleurs_ref")
maj('C-085','FAIT, EN ATTENTE DE TOM',"v139 : cadrage au doigt (`lot-V139-CADRE`) — deux doigts zooment 1:1 autour de leur milieu, un doigt déplace, z de 0,3 à 8 ; mémorisé sur la parole (`photoCadre`) et sur le brouillon de la page + ; « Enregistrer la photo » dans la vue en entier. Un Cercle ne porte pas de photo ; une photo n’est jamais dans une image partagée (v137) : rien à respecter au partage (Q434). Planche : `planche-v139/PLANCHE-3-photo.png`. À VALIDER SUR IPHONE (geste).","redteam_cadre 22/22 (8/21 avant) · redteam_entier 44/44 · redteam_photo_menu 20/20")
maj('C-086','FAIT, EN ATTENTE DE TOM',"v139 : tailles plume 2 · 6 · 14, gomme 8 · 18 · 36, points du choix à l’échelle ; disque PHOTO dans la rangée (pas des outils 58 → 46) : une ou plusieurs photos importées, chacune un élément du dessin, déplacée d’un doigt et redimensionnée au pincement quand PHOTO est choisi, posée avec le reste. Le dessin partagé n’emporte pas les photos importées (v137), à trancher (Q435). Planche : `planche-v139/PLANCHE-4-dessin.png`. À VALIDER SUR IPHONE (geste).","redteam_dessin_photo 15/15 · redteam_dessin 79/79 · redteam_partage_dessin 34/34")
maj('C-087','FAIT, EN ATTENTE DE TOM',"v139 : l’anneau passe de 84 à 60 pt, même centre : 12 pt d’air jusqu’au contour de la barre en haut et en bas ; épaisseur 13,5 gardée ; croix 27 de large dans un disque de 33 (82 % du disque, 46 % avant), à 3 pt de l’anneau. Capture cotée : `planche-v139/PLANCHE-5-plus.png`.","redteam_accueil 22/22 (cote réécrite)")
maj('C-088','FAIT, EN ATTENTE DE TOM',"v139 : DEUX CAUSES NOMMÉES. ① Trop zoomée : dans les douze mondes faits de leurs seules paroles, une parole = une cellule plein écran (Ritournelle et Bobinette n’y peignaient plus rien) ; sous neuf paroles et Cercles la Toile garde le semis constant des autres mondes (`SEMIS_NEUF_MIN`), Q437. ② Le toucher : sa durée était comptée à l’heure du traitement ; une image longue (1,15 s mesuré sous Ritournelle) entre l’appui et le lever le faisait jeter ; on compare les heures des événements. Non reproduit tel quel au banc sans image longue (Q438). Planches : `planche-v139/PLANCHE-7-ritournelle.png`, `PLANCHE-7b-douze-mondes.png`.","redteam_toucher (vingt mondes + trois contrôles Ritournelle : 5/5 sur Ritournelle, 2/5 avant) · banc_rendu · redteam_rythme")
prefixe('C-074',"v139 (Q429, Tom : « on ne comprend pas ce qu’elle montre ») : la main TRACE (la seconde moitié du trait devient pleine sous son doigt, puis s’efface), × 1,5, 1,6 s, trois passages ; ⚠ en E1 elle s’arrêtait au milieu du trait — un tracé qui, au vrai doigt, ne tient pas la parole et ne plante pas : elle va maintenant jusqu’au bout, fiche et page + (Q436). Les deux rangées aux Réglages (Q426). Planche : `planche-v139/PLANCHE-6-main.png`. À VALIDER SUR IPHONE. —")
io.open(f,'w',encoding='utf-8').write(S)
