import io,sys
S=io.open('app.html',encoding='utf-8').read(); L=S.split('\n')
MP='Ma Parole !'   # espace insécable, comme la porte des Réglages
T=[
# ——— L'OFFRE : le Cercle → Ma Parole ! ———
(3202,"'Le Cercle activé · Nuées illimitées'","'Tu es Membre "+MP+" · Cercles illimités'"),          # PROPOSITION (a)
(3218,"'✦ Membre du Cercle ✓'","'Tu es Membre "+MP+"'"),
(3220,"'Bienvenue dans le Cercle \\u2713 \\u00b7 tout Promi d\\u00e9bloqu\\u00e9'","'Tu es Membre "+MP+" \\u2713 \\u00b7 tout Promi d\\u00e9bloqu\\u00e9'"),  # PROPOSITION (b)
(3368,"'Bienvenue dans le Cercle ✓'","'Tu es Membre "+MP+" ✓'"),                                # PROPOSITION (b)
(3368,"'Le Cercle débloqué · Nuées illimitées'","'Tu es Membre "+MP+" · Cercles illimités'"),   # PROPOSITION (a)
(38501,"'Bienvenue dans le Cercle ✓ · tout Promi débloqué'","'Tu es Membre "+MP+" ✓ · tout Promi débloqué'"),  # PROPOSITION (b)
(16957,"\\u2726 Cercle \\u2014 vois la r\\u00e9ciprocit\\u00e9","\\u2726 "+MP+" \\u2014 vois la r\\u00e9ciprocit\\u00e9"),
(23958,"'✦ Le Cercle'","'✦ "+MP+"'"),
(37111,"'✦ Le Cercle'","'✦ "+MP+"'"),
(40181,">Avec le Cercle<",">Avec "+MP+"<"),
(40182,">✦ Le Cercle<",">✦ "+MP+"<"),
(40184,"'Les réglages du Cercle'","'Peaufiner, avec "+MP+"'"),   # PROPOSITION (c)
(41589,"'aria-label','Le Cercle'","'aria-label','"+MP+"'"),
(2548,'aria-label="Le Cercle"','aria-label="'+MP+'"'),
(2685,"· Le Cercle</span>","· "+MP+"</span>"),
(2719,'<div class="kc-t">Le Cercle</div>','<div class="kc-t">'+MP+'</div>'),
(2728,">Avec le Cercle<",">Avec "+MP+"<"),
(2728,"En activant ton Cercle, ton Noyau","Avec "+MP+", ton Noyau"),     # PROPOSITION (d)
(2774,">avec Le Cercle<",">Avec "+MP+"<"),
(2782,'<div class="pl-eb">Le Cercle</div>','<div class="pl-eb">'+MP+'</div>'),
(2785,"Le Cercle révèle",MP+" révèle"),
(2788,"Thèmes et matières exclusives au Cercle.","Thèmes et matières, avec "+MP+"."),   # PROPOSITION (e)
# l'écran qui vend (lot-CERCLE-TOILE et son titre)
(38742,"h:'Rejoins le Cercle !', sub:'ta parole, et celle qu’on te tient'","h:'"+MP+"', sub:'Retourne ta Toile'"),
(39193,"h1.textContent='Rejoins le ';","h1.textContent='Ma ';"),
(39194,"h2.textContent='Cercle';","h2.textContent='Parole';"),
(39195,"h3.textContent=' !';","h3.textContent='\\u00a0!';"),
(39198,"s1.textContent='ta parole, ';","s1.textContent='';"),
(39199,"s2.textContent='et celle qu’on te tient';","s2.textContent='Retourne ta Toile';"),
(39209,"lb.textContent='Essayer 14 jours';","lb.textContent='Bon, allez d’accord';"),
(41603,"if(h1 && h1.textContent!=='LE ') h1.textContent='LE ';","if(h1 && h1.textContent!=='MA ') h1.textContent='MA ';"),
(41604,"if(h2 && h2.textContent!=='CERCLE') h2.textContent='CERCLE';","if(h2 && h2.textContent!=='PAROLE') h2.textContent='PAROLE';"),
(41605,"if(h3 && h3.textContent!=='') h3.textContent='';","if(h3 && h3.textContent!=='\\u00a0!') h3.textContent='\\u00a0!';"),
# ——— LA NUÉE → LE CERCLE (masculin) ———
(2555,">Par Nuée<",">Par Cercle<"),(2555,">Nuées<",">Cercles<"),(2555,'data-s="nuee">Nuée<','data-s="nuee">Cercle<'),
(2578,'<div class="hname">Une Nuée</div>','<div class="hname">Un Cercle</div>'),
(2582,"<label>Dans une Nuée</label>","<label>Dans un Cercle</label>"),
(2587,"<label>Le nom de la Nuée</label>","<label>Le nom du Cercle</label>"),
(2588,"Les Promi de la Nuée","Les Promi du Cercle"),(2588,'aria-label="Trace pour lancer la Nuée"','aria-label="Trace pour lancer le Cercle"'),(2588,">Lancer la Nuée<",">Lancer le Cercle<"),
(2590,"<em>en Nuée</em>","<em>en Cercle</em>"),(2590,'</span>Nuée</button>','</span>Cercle</button>'),(2590,"<label>Dans quelle Nuée</label>","<label>Dans quel Cercle</label>"),
(2642,'placeholder="Rechercher un Promi, une Nuée…"','placeholder="Rechercher un Promi, un Cercle…"'),(2642,'data-s="nuee">Nuée<','data-s="nuee">Cercle<'),(2642,">Par Nuée<",">Par Cercle<"),(2642,">Nuées<",">Cercles<"),
(2653,'placeholder="de quoi parle cette Nuée ?"','placeholder="de quoi parle ce Cercle ?"'),
(2656,'placeholder="présente la Nuée, son but…"','placeholder="présente le Cercle, son but…"'),
(2657,"visible par la Nuée","visible par le Cercle"),
(2665,"Promesses de la Nuée","Promesses du Cercle"),
(2666,"Planter un Promi dans la Nuée","Planter un Promi dans le Cercle"),
(2668,">Dissoudre la Nuée<",">Dissoudre le Cercle<"),
(2670,">Promi en Nuée<",">Promi en Cercle<"),(2670,'data-dk="nuee">Nuée<','data-dk="nuee">Cercle<'),(2670,"Brouillon de Nuée. Prépare ici son thème, ses membres et ses premiers Promi, puis appuie sur Planter pour la créer.","Brouillon de Cercle. Prépare ici son thème, ses membres et ses premiers Promi, puis appuie sur Planter pour le créer."),
(2672,">Dans une Nuée<",">Dans un Cercle<"),
(2709,">Ta meilleure Nuée<",">Ton meilleur Cercle<"),
(2711,">Par Nuée · touche pour déplier<",">Par Cercle · touche pour déplier<"),
(2728,">Ta meilleure Nuée<",">Ton meilleur Cercle<"),
(2728,"La Nuée que tu honores le mieux ressort en premier — celle où","Le Cercle que tu honores le mieux ressort en premier — celui où"),
(2728,"selon la Nuée.","selon le Cercle."),
(2728,">Les graphs par Nuée<",">Les graphs par Cercle<"),(2728,"déclinées Nuée par Nuée","déclinées Cercle par Cercle"),
(2728,">Nuées illimitées &amp; designs<",">Cercles illimités &amp; designs<"),(2728,"Crée autant de Nuées que tu veux","Crée autant de Cercles que tu veux"),
(2737,"Promi, Toile, Nuée, Fil, Aura","Promi, Toile, Cercle, Fil, Aura"),
(2755,"dans une Nuée est partagé","dans un Cercle est partagé"),
(2766,"toile vide + 1 Nuée ›","toile vide + 1 Cercle ›"),
(2785,"chaque lien et chaque Nuée.","chaque lien et chaque Cercle."),
(2786,">Nuées illimitées<",">Cercles illimités<"),(2786,"Autant de cercles que tu veux","Autant de Cercles que tu veux"),
(2787,"par personne, par Nuée.","par personne, par Cercle."),
(2808,'<h2 id="esTitle">Nuée</h2>','<h2 id="esTitle">Cercle</h2>'),(2808,"renomme ou dissous cette Nuée","renomme ou dissous ce Cercle"),(2808,"<label>Nom de la Nuée</label>","<label>Nom du Cercle</label>"),
(2808,"+ Ajouter un Promi à la Nuée","+ Ajouter un Promi au Cercle"),(2808,">Aura de la Nuée<",">Aura du Cercle<"),(2808,">Nuée · membres<",">Cercle · membres<"),(2808,">Promesses de la Nuée<",">Promesses du Cercle<"),(2808,">Dissoudre la Nuée<",">Dissoudre le Cercle<"),
(3234,"'Donne un nom à ta Nuée'","'Donne un nom à ton Cercle'"),(3234,"'Tu as créé la Nuée '","'Tu as créé le Cercle '"),
(3550,"mot:'Nuée'","mot:'Cercle'"),
(3662,"' Nuée'+(m>1?'s':'')","' Cercle'+(m>1?'s':'')"),
(3698,"'Rejoins ma Nuée \\u00ab '","'Rejoins mon Cercle \\u00ab '"),
(3700,"'Dissoudre la Nuée ?'","'Dissoudre le Cercle ?'"),
(3775,"' \\u00b7 visible par la Nu\\u00e9e'","' \\u00b7 visible par le Cercle'"),
(4379,"'UNE NUÉE T’ATTEND'","'UN CERCLE T’ATTEND'"),
(4392,"'NUÉE REJOINTE'","'CERCLE REJOINT'"),
(4395,"pre:'NUÉE'","pre:'CERCLE'"),
(5322,"'aucune Nuée'","'aucun Cercle'"),
(5486,"nuee:'DANS QUELLE NU\\u00c9E'","nuee:'DANS QUEL CERCLE'"),
(5496,">aucune Nu\\u00e9e</span>",">aucun Cercle</span>"),
(5783,"estNueeF ? 'Nu\\u00e9e'","estNueeF ? 'Cercle'"),
(5820,"nomN = 'Cette Nu\\u00e9e'","nomN = 'Ce Cercle'"),(5821,"nomN = 'Cette Nu\\u00e9e'","nomN = 'Ce Cercle'"),
(5867,"</span>Planter dans la Nuée</button>'","</span>Planter dans le Cercle</button>'"),
(5868,'aria-label="Partager la Nu\\u00e9e"','aria-label="Partager le Cercle"'),
(6292,">en Nu\\u00e9e</button>",">en Cercle</button>"),(6293,">une Nu\\u00e9e</button>",">un Cercle</button>"),
(6700,"Ou il ouvre une <b style=\"color:#C9A8F5\">Nu\\u00e9e</b>","Ou il ouvre un <b style=\"color:#C9A8F5\">Cercle</b>"),
(6703,"et chacune de tes <b style=\"color:#F2D075\">Nu\\u00e9es</b>","et chacun de tes <b style=\"color:#F2D075\">Cercles</b>"),
(6779,"reprends une Nuée à la fois.","reprends un Cercle à la fois."),
(6792,"pas encore de Nuée à suivre","pas encore de Cercle à suivre"),
(7764,"<div class=\"sh-sg\">Nuées</div>","<div class=\"sh-sg\">Cercles</div>"),
(7774,"3 Nu\\u00e9es offertes pour toi","3 Cercles offerts pour toi"),
(15660,"les mêmes Promi et Nuées","les mêmes Promi et Cercles"),
(15747,"Nuées.</span>","Cercles.</span>"),
(16510,'"le nom de la Nuée…"','"le nom du Cercle…"'),(16511,'"Mettre la Nuée de côté"','"Mettre le Cercle de côté"'),
(16721,"' Nuée'+(m>1?'s':'')","' Cercle'+(m>1?'s':'')"),
(16722,'" Nu\\u00e9e"+(n>1?"s":"")','" Cercle"+(n>1?"s":"")'),
(16975,"_ty.textContent='Nuée'","_ty.textContent='Cercle'"),
(17210,"nuee:['Nouvelle','Nu\\u00e9e','#E6D8FA','une Nu\\u00e9e, et chacun y plante la sienne']","nuee:['Nouveau','Cercle','#E6D8FA','un Cercle, et chacun y plante la sienne']"),
(20949,"Je lance une Nuée</span><br><em>nommée</em> ","Je lance un Cercle</span><br><em>nommé</em> "),
(20959,"LE NOM DE LA NUÉE","LE NOM DU CERCLE"),
(21445,"'Plante le premier Promi de ta Nuée →'","'Plante le premier Promi de ton Cercle →'"),
(22691,"'nuee' ? 'Nuée' :","'nuee' ? 'Cercle' :"),
(23131,"mm.textContent='Nuée';","mm.textContent='Cercle';"),
(24021,"vis:'visibles par la Nuée'","vis:'visibles par le Cercle'"),
(24023,"'visibles par les membres de la Nuée'","'visibles par les membres du Cercle'"),
(24024,"'Planter un Promi dans la Nuée'","'Planter un Promi dans le Cercle'"),
(24026,"'DISSOUDRE LA NUÉE'","'DISSOUDRE LE CERCLE'"),
(24050,"'DANS UNE NUÉE'","'DANS UN CERCLE'"),
(25117,"'nuee' ? 'Nuée' :","'nuee' ? 'Cercle' :"),
(25621,"nuee:'Nu\\u00e9e'}","nuee:'Cercle'}"),
(25636,"'LES PROMI DE LA NU\\u00c9E'","'LES PROMI DU CERCLE'"),
(25654,"'DANS UNE NU\\u00c9E'","'DANS UN CERCLE'"),
(26854,"'#C9A8F5':'Nuée'","'#C9A8F5':'Cercle'"),(27003,"'#C9A8F5':'Nuée'","'#C9A8F5':'Cercle'"),
(28197,"'présente la Nuée, son but…'","'présente le Cercle, son but…'"),
(28199,"'visibles par la Nuée'","'visibles par le Cercle'"),
(28200,"'visibles par les membres de la Nuée'","'visibles par les membres du Cercle'"),
(28201,"'DISSOUDRE LA NUÉE'","'DISSOUDRE LE CERCLE'"),
(28329,"'Planter un Promi dans la Nuée'","'Planter un Promi dans le Cercle'"),
(39817,">Une Nuée<small>",">Un Cercle<small>"),
(39886,"' Nuée'+(m>1?'s':'')","' Cercle'+(m>1?'s':'')"),
(40184,"sur chaque Promi, Chiche et Nuée.","sur chaque Promi, Chiche et Cercle."),
(40956,"nuee:'Nuée'}","nuee:'Cercle'}"),
(42719,"une <b>Nuée</b> permet","un <b>Cercle</b> permet"),
]
bad=0
for n,o,nw in T:
    l=L[n-1]; c=l.count(o)
    if c<1: print('ABSENT',n,o[:80]); bad+=1; continue
    L[n-1]=l.replace(o,nw)
if bad: sys.exit(1)
io.open('app.html','w',encoding='utf-8').write('\n'.join(L)); print('ok',len(T))
